예외처리 
----

예외란 단순한 문법 오류가 아닌 실행 중간에 발생하는 정상적이지 않은 상황을 뜻한다. 가상머신은 예외의 원인은 알지만 프로그래머가 원하는 예외의 처리방식까지는 알지 못한다. 따라서 프로그래머는 자신이 의도하는 방향으로 예외처리를 해줘야한다.

### ■ try ~ catch

```java
try {
    // ... 관찰 영역 ... 
}
catch (Exception name) { 
    // ... 처리 영역 ...
}
```

try ~ catch 문법은 예외가 발생할 가능성이 있는 코드의 위치를 try로 감싸고 그것을 catch에서 처리하는 문법이다. 그리고 예외에 대한 내용은 catch 영역에서 예외 인스턴스로 인자에 전달되어 출력되거나 처리될 수 있다. 그렇게 되면 가상머신은 예외가 처리된 것으로 판단한다. 그렇기 때문에 가상머신은 예외에 대한 오류를 예외 메시지를 통해 사용자에게 경고만 내릴 뿐 오류를 일으키지 않는다. 그래서 가상머신은 다음 문장을 이어서 실행해 나갈 수 있다.

```java
public static void main(String[] args){
    Path file = Paths.get("C:\\javastudy\\Simple.txt");
    BufferedWriter writer = null;

    try{
        writer = Files.newBufferedWriter(file);
        writer.write('A');
        writer.write('Z');

        if(writer != null)
        writer.close();
    }
    catch(IOException e) {
        e.printStackTrace();
    }
}
```

위의 코드는 `"C:\\javastudy\\"` 경로에 `Simple.txt` 파일을 만들어 버퍼를 통해 `AZ`를 적고 파일을 닫는 코드이다. 코드를 보면 예외가 발생할 부분을 감싸고 catch에서 IOException 예외를 받아 처리하고 있다.

```java
try {
    // ...
}
catch( ArithmeticException | InputMismatchException e) { 
    // ... 
}
```

그리고 예외 처리해야 하는 것이 두개 이상이라면 위의 예시처럼 catch문을 연달아서 작성하거나 파이프라인으로 연결하여 예외에 대한 내용을 catch의 인자로 넣어주면 된다.

### ■ finally

finally 문법은 try...catch 이후에 반드시 실행되어야 하는 코드를 실행하는 문법이다. 따라서 try에서 예외가 발생되던 안되던, catch 문이 실행되던 안되던 무조건 실행된다. 그렇기 때문에 위의 코드에서 파일을 닫거나 하는 사후 처리시 사용될 수 있다.

```java
public static void main(String[] args){
    Path file = Paths.get("C:\\javastudy\\Simple.txt");
    BufferedWriter writer = null;

    try{
        writer = Files.newBufferedWriter(file);
        writer.write('A');
        writer.write('Z');
    }
    catch(IOException e) {
        e.printStackTrace();
    }
    finally {
        try{
            if(writer != null)
                writer.close();
        }
        catch(IOException e) {
            e.printStackTrace();
        }   
    }
}
```

위의 코드는 이전의 코드에서 close()와 같은 사후처리를 finally를 통해 구현한 모습이다. 하지만 close()에서도 IOException 예외가 발생할 수 있기 때문에 try ~ catch 문으로 예외 처리를 해줘야하는 것이 조금 아쉽다.

### ■ try-with-resources

```java
try ( resource ) {
    // ...
}
catch (Exception name) {
    // ...
}
```

try-with-resources를 사용하면 finally 에서 close()와 같은 사후처리를 해줄 때 위와 같은 번거로움을 없애 줄 수 있다. 먼저 예시의 try-with-resources에서 try는 메소드처럼 인자를 받고 있다. 그러나 그와 다르게 try 뒤의 소괄호는 종료 과정을 필요로 하는 리소스를 생성할 수 공간이 될 수 있다. 아래의 코드를 보자.

```java
public static void main(String[] args){
    Path file = Paths.get("C:\\javastudy\\Simple.txt");
    
    // 리소스가 여러개라면 세미콜론을 구분자로 하여 소괄호에 정의할 수 있다.
    try (BufferedWriter writer =  Files.newBufferedWriter(file)) {
        writer.write('A');
        writer.write('Z');
    }
    catch(IOException e) {
        e.printStackTrace();
    }
}
```

코드를 보면 이전 코드와 다르게 밖과 안에 있던 wirter의 정의가 소괄호 안으로 들어갔고 close() 구문이 사라진 것을 볼 수 있다. 그렇게 되는 이유는 리소스들을 소괄호 안에 정의하면 java.lang.AutoCloseable 인터페이스가 자동으로 해당 리소스를 try가 끝날 때 종료시키기 때문이다. 

그렇다면 리소스는 어떻게 자동 종료되는 것일까? 그것은 바로 AutoCloseable 인터페이스가 close() 메소드를 추상메소드로 두고 있고 리소스들은 AutoCloseable 인터페이스를 구현해야하기 때문이다. 그렇기 때문에 위와 같이 리소스의 자동 종료가 가능하다.

따라서 이처럼 try-with-resources를 사용하면 코드가 매우 간결해지고 가독성이 좋아지는 효과를 얻을 수 있다.

### ■ Throwable 클래스

예외 클래스의 최상위 클래스는 java.lang.Throwable이다. 해당 클래스는 아래의 메소드를 지니고 있다.

- getMessage() : 예외의 원인을 담고 있는 문자열을 반환
- printStackTrace() : 예외가 발생한 위치와 호출된 메소드의 정보를 출력

printStackTrace() 메소드는 예외처리하지 않았을 때 콘솔에 출력되는 내용이다. 아래의 코드를 실행하면 printStackTrace()의 출력을 볼 수 있다.

```java
public static void md1(int n){
    md2(n, 0);
}
public static void md2(int n){
    int r = n1 / n2
}
public static void main(int n){
    md1(3);
    System.out.println("Good bye~~!");
}
```
```
Exception in thread "main" java.lang.ArithmeticException: / by zero
    at Study/study.HelloJava.md2(HelloJava.java:16)
    at Study/study.HelloJava.md1(HelloJava.java:13)
    at Study/study.HelloJava.main(HelloJava.java:19)
```

그런데 출력 값을 보면 md2, md1, main 순으로 printStackTrace() 출력 값이 나타나는 것을 볼 수 있다. 이것은 특정 메소드에서 예외처리를 하지 않을 시 이전에 스택에 쌓였던 메소드에게 예외를 처리하도록 위임하기 때문이다. 그리고 그러다 보면 가상머신에게도 예외처리가 넘겨지는데 그럴 때 가상머신도 printStackTrace()를 호출하여 예외처리를 한다.

그렇기 때문에 예외는 가상머신에게 넘겨지기 전에 어느 한 메소드 내에서 필수적으로 처리해줄 필요가 있다.

<hr>

지금부터는 Throwable 클래스를 상속하는 클래스에 대해서 알아볼 것이다.

Throwable 클래스를 상속하는 클래스는 Error, RuntimeExcepiton, Exception 클래스가 있다. RuntimeException 클래스는 Exception 클래스를 상속하여 Throwable 클래스를 간접 상속하는 클래스이다. 

그런데 RuntimeExcepiton 클래스와 Excepiton 클래스를 따로 소개하는 이유는 Exception을 상속하는 클래스(RuntimeExcepiton 제외)와 RuntimeExcepiton 클래스에는 차이점이 있기 때문이다.

#### ► Error 클래스

먼저 Error 클래스이다. Error 클래스를 상속하는 클래스는 다음과 같다.

- VirtualMachineError : 가상머신에 심각한 오류 발생 예외
- IOErorr : 입출력 관련해서 코드 수준 복구가 불가능한 오류 발생 예외

Error 클래스를 상속하는 클래스는 예외 처리의 대상이 아니다. 두 에러 모두 하드 디스크의 물리적 오류나 메모리 공간 부족과 같은 하드웨어의 에러때문에 발생한 에러이다. 그렇기 때문에 사용자가 처리할 수 있는 에러가 아니다. 그래서 예외처리의 대상이 될 수 없다.

#### ► RuntimeExcepiton 클래스

다음은 RuntimeExcepiton 클래스이다. RuntimeExcepiton 클래스를 상속하는 클래스는 다음과 같다.

- ArithmeticException : 예외적인 산술조건에 대한 예외
- InputMismatchException : 잘못된 입력에 대한 예외
- ArrayIndexOutOfBoundsException : 배열의 잘못된 인덱스 접근 예외
- ClassCastException : 허용할 수 없는 형 변환을 강제로 진행했을 때의 예외
- NullPointerException : null이 저장된 참조변수를 대상으로 메소드를 호출할때 발생하는 예외
- IndexOutOfBoundsException : 인덱스가 범위를 벗어났을 때 발생하는 예외
- NegativeArraySizeException : 배열 생성시 길이를 음수로 지정하는 예외의 발생
- ArrayStoreException : 배열에 적합하지 않는 인스턴스 저장에 대한 예외

Error 클래스를 상속하는 클래스 또한 프로그래머가 일일이 예외처리를 하지 않는다. 물론 상황에 따라 개발자가 예외를 처리해야할 경우도 있지만 대부분은 예외처리가 아닌 코드를 수정해야하는 상황이다. 왜냐하면 예외가 발생하는 상황의 대부분이 사용자 입력에 대한 오류를 통해 예외가 발생하는 상황이기 때문이다. 그렇기 때문에 예외처리 보단 사용자 입력을 예상하여 코드를 수정해야한다.

#### ► Exception 클래스

마지막으로 Exception 클래스이다. Exception 클래스를 상속하는 클래스 즉, 위의 RuntimeExcepiton 클래스 이하를 제외한 Exception 클래스만 상속하는 클래스는 다음과 같다.

- IOException : I/O 오류가 발생하는 경우에 발생하는 예외

Exception 클래스를 상속하는 클래스가 하나 인 이유는 그 수가 너무 많기 때문이다. 그렇기 때문에 IOException 클래스만 설명하기로 하고 나머지는 직접 찾아보고 사용하길 바란다.

그리고 앞서 Exception 클래스는 다른 두 클래스와 다른 특징이 있다고 하였다. 그것은 바로 Exception 클래스를 상속하는 클래스는 모두 의무적으로 try..catch를 통해 예외처리를 해줘야한다는 점이다.

그 이유는 자바에서 특별히 Exception 클래스를 상속하는 클래스에만 예외처리를 하지 않았을 때 오류가 발생하도록 강제해두었기 때문이다. 그렇기 때문에 Exception 클래스 때문에 자바에서는 예외처리가 필수라고 하는 말도 있다. (사용자 정의 예외 클래스도 Exception 클래스를 상속한다.)

따라서 Exception 클래스가 아닌 위의 것들은 의무적으로 예외처리를 해줄 필요가 없기 때문에 위에서 Error나 RuntimeExcepiton 클래스의 코드로 쉬운 예시를 들 수 있었음에도 필자는 IOException 클래스를 예시를 들었다.

### ■ 사용자 정의 예외 클래스

지금까지 알아본 예외 클래스는 모두 자바에 미리 정의되어 있는 클래스이다. 그러나 자바에서는 프로그래머가 직접 예외 클래스를 정의하고 이를 기반으로 특정 상황에서 예외가 발생하도록 의도할 수 있다. 그 방법은 다음과 같다.

- Exception 클래스를 상속하여 사용자 정의 예외 클래스를 만들 수 있다.
- Exception 클래스를 상속하면 getmessage() 메소드를 사용할 수 있다.
    - 만들어진 예외클래스의 생성자에서 메시지를 super()의 인자로 전달하면 그 메시지가 getmessage()를 통해서 출력된다.

또한 위의 코드 중에서 printStackTrace() 코드로 이전 스택의 메소드에 예외처리를 위임한다고 예시를 들었다. 이와 관련된 문법이 있다.

- throws : 해당 메소드를 호출한 이전 메소드가 예외를 처리하도록 위임할 수 있으며 예외에 대한 내용을 입력해야한다. 
- throw : 예외 발생하는 부분에 `throw new excpClass()`를 입력해서 의도적으로 예외처리를 할 수 있다. 이는 프로그래머가 일반적인 오류가 아닌 일반 사용자의 입력을 임의의 오류로 정의할 수 있다.

```java
class ReadAgeException extends Exception{
    public ReadAgeException() {
        super("유효하지 않은 나이가 입력되었습니다.");
    }
}

class HelloJava{
    public static void main(String[] args){
        System.out.print("나이 입력 : ");
        
        try {
            int age = readAge();
            System.out.printf("입력된 나이 : %d \n", age);
        }
        catch(ReadAgeException e) {
            System.out.println(e.getMessage());
        }
    }
    
    public static int readAge() throws ReadAgeException {
        Scanner kb = new Scanner(System.in);
        int age = kb.nextInt();
        
        if(age < 0)
            throw new ReadAgeException();
        
        return age;
    }
}
```
```
나이 입력: -7
유효하지 않은 나이가 입력되었습니다.
```

위의 코드를 보면 프로그래머가 직접 예외 클래스르 만들어서 오류 메시지를 출력하는 것을 볼 수 있다. 코드에서는 readAge() 메소드를 부르기 전의 main() 메소드로 예외처리를 위임했고 throw를 통해 임의적인 오류를 발생시켜 사용자에게 알려주는 것을 볼 수 있다.

지금까지 예외처리에 대해서 알아보았다. 하지만 내의 코드는 try 밖의 코드에 비해 실행속도가 느리기 때문에 성능의 저하로 이어질 수 있다. 따라서 과도한 예외처리는 지양하도록 하자.

열거형, 가변인자, 어노테이션
-----

### ■ 열거형

열거형은 의미가 부여된 이름을 갖는 상수이다. 열거형은 현재의 열거형과 과거의 열거형, 두 방법이 있다. 지금은 사용되지 않지만 현재의 열거형을 이해하기 위해 과거의 열거형을 먼저 살펴보고 왜 현재의 열거형이 생겨났는지 알아보도록 하자.

과거의 열거형은 하나의 인터페이스에 변수(public, static, final)를 선언하고 그 변수에 특정 정수를 부여하는 방식이였다. 즉 일반적인 final 값을 열거형에 사용한 것이다.

하지만 그 방법을 사용하면 열거형으로 정의된 인터페이스 변수 값이 일반적인 정수 값이기 때문에 그 값이 다른 열거형 인터페이스의 변수 값과 겹치게 되어 비정상적인 논리 오류가 발생하는 문제가 생긴다.

이 문제는 문법이나 실행에 대한 오류가 아닌 논리적인 오류이기 때문에 컴파일 에러나 실행 에러가 발생하지 않아 더 치명적인 결과를 초래할 수 있다. 아래의 코드를 보자.

```java
interface Animal {
    int DOG = 1; int CAT = 2;
}
interface Person {
    int MAN = 1; int WOMAN = 2;
}

class HelloJava{
    public static void who(int man) {
        switch(man) {
        case Person.MAN:
            System.out.println("남성 손님입니다.");
            break;
        case Person.WOMAN:
            System.out.println("여성 손님입니다.");
            break;
        }
    }
    public static void main(String[] args) {
        who(Person.MAN);  // 정상적인 메소드 호출
        who(Animal.DOG);  // 비정상적인 메소드 호출 => 오류가 발생하지 않음 // 논리적 오류
    }
}
```
```
1
1
```

위 코드에서 Animal 열거형과 Person 열거형이 다른 열거형이기 때문에 정상적인 로직이라면  `who(Animal.DOG);` 절에서 오류가 발생해야한다. who 메소드를 구현한 개발자는 Person의 인스턴스의 멤버만 받도록 코드를 의도하였다. 하지만 Animal.DOG와 Person.MAN이 같은 정수 값을 지니고 있어 메소드 진입은 물론이며 같은 값이 출력되는 상황이 발생한다. 이것은 논리적 오류이며 개발자의 의도가 아니기 때문에 치명적일 수 있다.

따라서 앞의 문제점을 해결하기 위해 현재의 열거형인, 열거형(enum)이 만들어 졌다. 

열거형은 클래스와 성격이 유사하다. 그렇기 때문에 참조변수의 선언도 가능하며 그 참조변수에는 같은 열거형 값만 담을 수 있도록 되어있다. 그렇기 때문에 열거형 참조변수에 같은 열거형 값의 대입만 가능하다는 점에서 앞서 발생한 논리적 오류 문제를 해결할 수 있다. 아래의 코드를 보자.

```java
enum Animal {
    DOG, CAT
}
enum Person {
    MAN, WOMAN
}

class HelloJava{
    public static void who(Person man) {
        switch(man) {
        case MAN:
            System.out.println("남성 손님입니다.");
            break;
        case WOMAN:
            System.out.println("여성 손님입니다.");
            break;
        }
    }
    public static void main(String[] args) {
        who(Person.MAN);     // Person man = Person.MAN | 정상적인 메소드 호출 
        // who(Animal.DOG);  // Person man = Animal.DOG | 비정상적인 메소드 호출 (에러 발생)
    }
}
```
```
1
```

코드를 보면 interface가 아닌 enum 키워드를 통해서 열거형을 구현하였고 who 메소드 매개변수에 Person man이라는 참조변수형을 인자로 부여하였다. 그런데 main 내부에서 `who(Animal.DOG);` 코드를 실행하면 에러가 발생하는 것을 볼 수 있다. 그 이유는 Animal.DOG은 Person man과 참조변수형이 다르기 때문이다. 따라서 에러가 발생하였고 위의 문제는 해결되었다.

그리고 열거형은 클래스 내부에도 정의될 수 있다. 그렇기 때문에 특정 클래스 내부에서만 사용하는 열거형을 구현할 수 있다.

#### ► 열거형의 정체

1\. 앞서 열거형은 클래스와 유사하다고 하였으나 사실 열거형은 클래스의 종류 중 하나이다. 왜냐하면 모든 열거형은 java.lang.Enum<E\> 클래스를 상속하며 Enum<E\>은 Object 클래스를 상속하기 때문이다.

2\. 클래스의 문법 중 클래스 내부에서 자신의 클래스형 참조변수를 선언하고 그 참조변수를 통해 인스턴스를 생성할 수 있다. 그러한 방법으로 열거형 값이 만들어진다. 열거형 값은 자신의 클래스 내에서 public static final로 선언한 자신의 인스턴스이다. 이와 같이 자신의 인스턴스를 자신의 클래스 내에 선언한 이유는 인스턴스 고유의 참조값(인스턴스 값, 주소값)을 이용하여 그것을 외부에서 멤버 변수처럼 사용하려는 목적 때문이다.

```java
enum Person{
    MAN  // public static final Person MAN = new Person(); // (동일)
}
```

3\. 열거형 값은 생성자를 통해 생성된다. 그런데 열거형의 생성자는 private으로 선언되어 있다. 그 이유는 private으로 선언되어야 외부에서 생성자를 사용할 수 없다. 열거형의 값은 열거형 외에 다른 곳에서 생성되면 안되기 때문에 생성자를 private로 선언한다.

4\. 열거형도 클래스이기 때문에 생성자를 오버로딩(private), 메소드 정의, 멤버 변수 정의, 메소드 오버라이딩 모두 가능하다. 그런데 인스턴스의 생성이 열거형 내부에서만 가능하기 때문에 생성자를 통해서 멤버 변수 값을 부여하고 싶다면 열거형 값을 정의할 때 인자로 값을 넣어줘야한다.

```java
enum Person{
    MAN(29),        // public static final Person MAN = new Person(29);
    WOMAN(25);      // public static final Person MAN = new Person(25);

    int age;
    
    private Person(int age) { this.age = age; }
    
    @Override
    public String toString() { return "I am " + age + "years old";}
}

class HelloJava{
    public static void main(String[] args) {
        System.out.println(Person.MAN);
        System.out.println(Person.WOMAN);
    }
}
```

위의 코드를 보면 열거형에도 멤버 변수 정의, 메소드 정의, 메소드 오버라이딩이 모두 가능한 것을 볼 수 있으며 생성자에 따른 인자 값 부여도 열거형 값을 정의할 때 넣는 것을 볼 수 있다. 

마지막으로 열거형에서 가장 중요한 점을 정리하자면 다음과 같다. 열거형 값, 즉 열거형 인스턴스는 열거형 내부에서만 선언이 가능하다는 것과 열거형 내부 생성자는 private로 선언되어 외부에서 열거형 값(인스턴스)를 정의할 수 없게 해야한다는 점이다. 또한 열거형은 상수를 부여하는 방식에서 인스턴스의 고유성을 이용하여 의미있는 상수를 만든다는 것을 꼭 알고 넘어가자.

### ■ 매개변수의 가변 인자 선언

메소드의 매개변수를 선언할 때 가변 인자 선언을 하면 전달되는 인자의 수에 제한을 두지 않을 수 있다.

이는 아래의 주석처리 된 코드를 편리하고 직관적으로 사용할 수 있도록 바꾼 것이며 컴파일러에서 주석처리된 코드로 변경되어 작동한다.

```java
public static void showAll(String...vargs) {  //(String[] vargs)
    System.out.println("LEN : " + vargs.length);

    for(String s : vargs)
        System.out.print(s + '\t');
    System.out.println();
}

public static void main(String[] args){
    showAll("Box");                      // showAll(new String[]{"Box"});
    showAll("Box", "Toy");               // showAll(new String[]{"Box", "Toy"});
    showAll("Box", "Toy", "Apple");      // showAll(new String[]{"Box", "Toy", "Apple"});
}

```

※ length vs length() vs size()

- length : 배열의 길이를 알고자 할때 사용된다.
- length() : 문자열의 길이를 알고자 할때 사용된다.
- size() : 컬렉션프레임워크(ArrayList, Set..등) 타입의 길이를 알고자 할때 사용된다.

### ■ 어노테이션 

어노테이션은 자바가 컴파일러에게 메시지를 전달하는 일종의 메모이다. 간단하게 세가지의 어노테이션만 알아보고 부족하다면 www.jcp.org에 더 많은 것이 있으니 찾아보길 바란다.

#### ► @Override

- 실수로 오버라이딩 안되있을 때 에러를 일으키기 위해 상위 클래스의 메소드의 오버라이딩을 컴파일러에게 알리는 것이다.
- @Override 어노테이션은 상위 클래스의 메소드 오버라이딩 또는 인터페이스에 선언된 추상 메소드의 구현시 사용된다.

#### ► @Deprecated

- 문제 발생 소지가 있거나 다른 개선된 기능으로 대체되어 더 이상 필요 없게 되었음을 뜻하는 어노테이션이다.
- 호환성 유지로 존재하나 이후에 사라질 가능성이 있는 클래스와 메소드에 @Deprecater 어노테이션을 사용한다.
- @Deprecated 어노테이션를 사용하면 컴파일러가 그 메소드나 클래스를 사용했을 때 아래의 문장으로 경고문을 보낸다.

```
Note: XXX.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details. // -Xlint:deprecation 옵션으로 다시 컴파일 하라는 뜻.
```

#### ► @SuppressWarnigs

- @SuppressWarnigs() 어노테이션을 사용하면 컴파일러에게 경고 메시지를 전달하지 않도록 요청할 수 있다. 즉 경고메시지가 오지 않는다.
- 어노테이션 인자에 지우고 싶은 경고에 대한 내용을 넣어서 경고를 지울 수 있다.
- 기존의 어노테이션으로 설정된 경고도 덮어 씌울 수 있다.

```java
// ex)
@SuppressWarnigs("deprecation")                   // deprecation 경고 삭제
@SuppressWarnigs("fallthrough")                   // fallthrough 경고 삭제 ( fallthrough 경고 : ex) break 없는 switch 문 )
@SuppressWarnigs({"fallthrough", "deprecation"})  // 둘 아상의 경고 삭제 요청
```